### PR TITLE
Adding La Rosiere (France) and La thuile (Italy)

### PR DESCRIPTION
**Pull request by readingdancer**
I've added both the above mentioned resorts, it is working fine locally, although four of the existing resorts are failing due to their pages changing. I am not sure why the build of my last pull request failed, if you can let me know what I did wrong it would be useful?

### CODE REVIEW

**Comment by readingdancer** [comment]
I have fixed the errors in the last couple of commits.

**Comment by pirxpilot** [comment]
Thank you! [La Rosière] is now live on liftie.into

- 767ebe9 these are all your changes squashed to a single commit with cleaned up whitespace
- 05d545d minor descriptor fixes
- 71f7566 simplified parser

Please have a look at my changes, check if I didn't break anything and let me know if you have any questions.

Now - one thing I don't quite get. You wrote: _I've added both the above mentioned resorts_
 but unless I missed something there was only a single resort.json in the PR. Are you still thinking about adding La Thuile as a separate resort?
Also you are up for fixing some of the defunct ones the full list is here: https://liftie.info/absent

In any case: thanks again. See you on the slopes! 
[La Rosière]: https://liftie.info/resort/larosiere

**Comment by readingdancer** [comment]
Hi,
Thanks for the code changes, I kinda assumed there was an easier way to parse the page with your current code, it would be really useful if you could add some examples to your docs describing how your helper functions should be used, it would have helped newbies like me save a few hours ;)

As for La Thuile, I did add it, so it seems I have not added all the files to the commit which is annoying, unfortunately this was in my iMac in the office so it will need to wait until Monday. 

I noticed one of your broken resorts now uses a page built by iSki and looking at the source it has an xml data feed, have you got an example of parsing an XML API feed? If we get that working, I would guess it could open up a lot more resorts.

**Comment by pirxpilot** [comment]
> Thanks for the code changes, I kinda assumed there was an easier way to parse the page with your current code, it would be really useful if you could add some examples to your docs describing how your helper functions should be used, it would have helped newbies like me save a few hours ;)

Sure.  I am always thinking that there are over 100 examples in the code but that's probably too many :-) BTW: Did you use the `generate` script from [How to add a new resort][3] section?

> As for La Thuile, I did add it, so it seems I have not added all the files to the commit which is annoying, unfortunately this was in my iMac in the office so it will need to wait until Monday.

Ah... Hate when that happens. Anyway - you can create a new PR when you have a chance. Please rebase and squash if needed. If parser is shared between the two move it to the `tools` directory.

> I noticed one of your broken resorts now uses a page built by iSki and looking at the source it has an xml data feed, have you got an example of parsing an XML API feed? If we get that working, I would guess it could open up a lot more resorts.

Parsing XML in Liftie is no different than parsing HTML. Some examples: [smugs][1], [rixml][2] - basically you can as close as possible with CSS selector and the traverse node to get to the data. I'll help if you get stuck.

[1]: https://github.com/code42day/liftie/blob/master/lib/resorts/smuggs/index.js
[2]: https://github.com/code42day/liftie/blob/master/lib/tools/rixml.js
[3]: https://github.com/code42day/liftie#how-to-add-your-favorite--acmecom-resort

**Pull request closed without merging**
