### PR TITLE
Stantonamarlberg

### PR DESCRIPTION
**Pull request by srocki**
Adding scraper and test for St Anton Am Arlberg, Austria

### CODE REVIEW

**Comment by pirxpilot** [comment]
Thanks for the PR! I'll try to get it in this weekend.

**Comment by srocki** [comment]
No worries, no rush on this

**Comment by pirxpilot** [comment]
St. Anton support has been release as a part of 3.15.0 and should be online now.
Thanks for the PR - if you want review my changes on top of your branch.
Let me know if you have any questions.

**Comment by srocki** [comment]
Thanks! Changes all make sense to me and it looks good on liftie

**Pull request merged**
